초기환경설정
Im-D/your-voice-front pull request #1
Opened 2021-01-28 14:44 UTC by dididy

- [ ]  Jest
- [x] Storybook
- [x] Vite + TypeScript + React + (Module alias)
- [x] Recoil
  - [ ] 봉기님이 요청하신 부분
- [x] SASS(SCSS)
- [x] eslint + husky(lint-stage) + commitlint

2021-01-29 09:23 UTC, SeonHyungJo commented
그때 말씀드린바와 같이 tsconfig에서 alias 같은 path를 추가해주시면 됩니다.

2021-01-29 09:24 UTC, SeonHyungJo commented
storybook의 파일은 src 안에 있어야하나요?

2021-01-29 09:24 UTC, SeonHyungJo commented
reset css가 등록되어있는 걸까요?

2021-01-29 09:25 UTC, SeonHyungJo commented
같이 폴더구조에 대해서도 논의하시죠 @dididy @BKJang

2021-01-29 09:26 UTC, SeonHyungJo commented
vite.config.ts에서도 alias 설정이 안되어있는거 같습니다.

2021-02-01 06:08 UTC, BKJang commented on .storybook/preview.js
> +}
EOL 추가해주세여

2021-02-01 06:08 UTC, BKJang commented on .vscode/settings.json
> +  }
EOL 추가해주세여

2021-02-01 06:09 UTC, BKJang commented on src/App.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
불필요한 주석같은데, 불필요하다면 지우면 좋을 것 같습니다

2021-02-01 06:11 UTC, BKJang commented on src/store/states.ts
> +});
```js
export const countState = key => atom({
  key,
  default: 0,
});
```

이런식으로 하면 어떨까 제안드린거였습니다.

2021-02-01 06:11 UTC, BKJang commented on src/store/states.ts
> +});
`export const countState = key => atom({
  key,
  default: 0,
});`

2021-02-01 06:12 UTC, BKJang requested changes
거의 다 세팅된 것 같네요.
몇 가지 리뷰 남겼는데 의견주시면 좋을 것 같아요.
고생하셨습니다 👍

2021-02-01 14:50 UTC, dididy commented on src/store/states.ts
> +});
```javascript
export const getCountState = key = selector({
  key,
  get: ({ get }) => get(countState),
});
```
요렇게를 의도하신거죠?

2021-02-01 14:51 UTC, dididy commented on src/store/states.ts
> +});
네이밍은 그대로 가도 될까요? 뭔가 일반화되는 느낌이라 지금이름은 적절치 않은 것 같아서요

2021-02-01 16:54 UTC, BKJang commented on src/store/states.ts
> +});
naming도 general하게 바뀌면 좋을 것 같네요 👍

2021-02-08 16:08 UTC, BKJang approved these changes
고생하셨습니다.
어차피 하다가 조금씩 수정할 일이 생길 수 있으니 개인적인 의견으로는 이 정도면 충분할 것 같습니다.

2021-02-12 06:55 UTC, SeonHyungJo approved these changes
수고하셨습니다.

2021-02-12 06:55 UTC, merged