[component/image] Image 컴포넌트 개발
Im-D/your-voice-front pull request #21
Opened 2021-03-07 12:19 UTC by dididy

> resolve #11 

- alias 설정 제대로 안된 부분 다시 수정(Jest alias 경로도 추가적으로 수정)
- @testing-library/jest-dom의 matcher 사용할 수 있도록 설정 추가
- 컴포넌트 및 테스트코드 추가

2021-03-10 16:22 UTC, BKJang requested changes
확인부탁드립니다 🙏

2021-03-10 16:22 UTC, BKJang commented on jest.config.js
>      "^@components(.*)$": "<rootDir>/src/components$1",
```suggestion
    '^@components(.*)$": "<rootDir>/src/components$1',
```
왜 해당 라인만 double quote 일까요? 수정이 필요할듯합니다.

2021-03-10 16:22 UTC, BKJang commented on jest.setup.js
> +import "@testing-library/jest-dom/extend-expect";
```suggestion
import '@testing-library/jest-dom/extend-expect';
```
single quote로 수정해주세여

2021-03-10 16:22 UTC, BKJang commented on src/pages/Main.tsx
> +        <Image
Image 컴포넌트에서 `alt` property가 필수 값으로 보이는데 에러가 발생하지 않나요?

2021-03-10 16:22 UTC, BKJang commented on src/pages/Main.tsx
>          </p>
button 부분은 불필요한 코드 같아 보입니다. 주석 처리가 아니라 삭제하는게 좋을 것 같아요

2021-03-10 16:22 UTC, BKJang commented on src/atoms/Image/index.tsx
> +  height,
@SeonHyungJo @dididy width, height property에는 default parameter를 넣으면 좋을 것 같은데 어떻게 생각하시나요?

2021-03-10 16:26 UTC, dididy commented on jest.config.js
>      "^@components(.*)$": "<rootDir>/src/components$1",
이 부분은 alias PR에 반영하도록 하겠습니다.

2021-03-10 16:30 UTC, SeonHyungJo requested changes
의견을 남겼습니다. 확인부탁드립니다.

2021-03-10 16:30 UTC, SeonHyungJo commented on jest.config.js
>      "^@components(.*)$": "<rootDir>/src/components$1",
그보다 우선적으로 해당 branch에 맞지 않는 파일로 보입니다. @dididy @BKJang

2021-03-10 16:30 UTC, SeonHyungJo commented on jest.setup.js
> +import "@testing-library/jest-dom/extend-expect";
테스트 코드는 별로의 PR로 가져가는건 어떤가요? 지금 안 맞아보이네요 @dididy @BKJang

2021-03-10 16:30 UTC, SeonHyungJo commented on src/atoms/Image/index.tsx
> +  height,
넣는 건 좋다고 생각합니다. 추가적으로 style에도 넣는게 좋아보입니다. @dididy @BKJang 

막연하게 optional은 기본값이 있는게 맞다고 생각하는 입장입니다.

2021-03-10 16:30 UTC, SeonHyungJo commented on src/pages/Main.tsx
> +        <Image
이 부분도 개발시 사용하는 것은 조으나 커밋에는 포함안되도록하는게 좋아보입니다.

2021-03-10 16:34 UTC, dididy commented on src/pages/Main.tsx
>          </p>
반영하였습니다.

2021-03-10 16:35 UTC, dididy commented on src/pages/Main.tsx
> +        <Image
console에서 에러를 냈지만 제가 인지 못하고 푸시한 것 같습니다. alt 추가하였습니다.

2021-03-10 16:35 UTC, voidmatcha commented on jest.setup.js
> +import "@testing-library/jest-dom/extend-expect";
jest 설정을 위해 새로 만들어둔 PR에 반영하였습니다.

2021-03-10 16:36 UTC, dididy commented on src/pages/Main.tsx
> +        <Image
아 선형님 코멘트를 지금봤네요..

2021-03-10 16:48 UTC, dididy commented on src/atoms/Image/index.tsx
> +  height,
두분 의견대로 default parameter를 넣도록 하겠습니다.

@SeonHyungJo style에도 넣는게 어떤걸 의미하나요?

2021-03-10 16:49 UTC, dididy commented on src/pages/Main.tsx
> +        <Image
@SeonHyungJo 포함 안되도록 리베이스 하도록 하겠습니다

2021-03-10 16:57 UTC, dididy commented
jest나 alias 설정 및 그에따른 컨벤션 문제는 PR을 따로 빼서 처리하였습니다.

2021-03-11 08:49 UTC, SeonHyungJo commented on src/atoms/Image/index.tsx
> +  height,
지금 style의 기본값은 null로 보입니다. 그보다 style에도 기본값이 있는게 맞아보입니다 @dididy

2021-03-11 11:54 UTC, dididy commented on src/atoms/Image/index.tsx
> +  height,
@SeonHyungJo style 및 className props에 default parameter넣었습니다!

2021-03-11 15:37 UTC, SeonHyungJo approved these changes
수고하셨습니다. 승인하겠습니다.

2021-03-15 16:10 UTC, BKJang approved these changes
고생하셨습니다 👍

2021-03-15 16:10 UTC, merged