[fix/alias] vite 및 jest alias에서 @atoms 누락된 부분 추가
Im-D/your-voice-front pull request #22
Opened 2021-03-10 16:11 UTC by dididy

> resolve #5

2021-03-11 15:28 UTC, SeonHyungJo commented on jest.config.js
> +    '^@organisms(.*)$': '<rootDir>/src/components/organisms$1',
이 부분이 꼭 필요할까요? @dididy

2021-03-11 15:28 UTC, SeonHyungJo requested changes
확인부탁드립니다.

2021-03-11 15:43 UTC, dididy commented on jest.config.js
> +    '^@organisms(.*)$': '<rootDir>/src/components/organisms$1',
@SeonHyungJo 또 놓쳤네요 삭제하고 `@`랑 `@styles` 추가 안되어있던 것 추가하였습니다!

2021-03-11 15:45 UTC, SeonHyungJo approved these changes
승인합니다.

2021-03-21 07:04 UTC, BKJang approved these changes
고생하셨습니다 👍

2021-03-21 07:04 UTC, merged