[feat/api] API 공통 구현
Im-D/your-voice-front pull request #3
Opened 2021-02-22 10:37 UTC by BKJang

## API 공통 구현
- eslint rule 추가 : "import/prefer-default-export": 'off'
  - export default만 쓰도록 권장하는 lint
  - util이나 api의 경우 export를 쓰는게 권장되는 형태도 있어 off 처리
- alias추가: @api
- `axios` 추가
- api 공통 모듈 구현
  - 서버와 맞추는 과정에서 수정 필요
  - controller 분리 작업 완료하였고 리뷰 필요

2021-02-23 03:10 UTC, SeonHyungJo requested changes
확인해주세요.

2021-02-23 03:10 UTC, SeonHyungJo commented on src/api/controllers/Question.ts
> +}
Interface도 좋은 방법이지만 여기서는 type으로 정의하는게 좋아보입니다. 나중에 extends해서 사용할 일이 생기면 그때 바꾸는게 좋습니다.

2021-02-23 03:10 UTC, SeonHyungJo commented on src/api/controllers/utils.ts
> +  message: string | number;
왜 string과 number 둘 다 되도록 되어있나요?

2021-02-23 03:10 UTC, SeonHyungJo commented on src/api/controllers/utils.ts
> +const parseResult = (res: TApiReturn): any => {
any보다는 같이 다른 타입으로 반환하도록 바꿔보시죠

2021-02-23 03:10 UTC, SeonHyungJo commented on src/api/controllers/utils.ts
> +    });
```suggestion
    const res = await axios({
      ...options,
      url
    });
```

위의 코드로 변경하는 것은 별루인가요?

2021-02-23 03:10 UTC, SeonHyungJo commented on src/api/controllers/utils.ts
> +    const data: any = await parseResult(res.data);
여기서 `const data`는 알아서 타입추론이 되어서 any라고 적어주지 않아도 됩니다.

2021-02-23 03:18 UTC, SeonHyungJo commented on src/api/controllers/utils.ts
> +const parseResult = (res: TApiReturn): any => {
```ts
const parseResult = (res: TApiReturn): Pick<TApiReturn, 'data'> | Error => {
  if (!res.isSuccess) {
    throw new Error('res.isSuccess is false');
  }
  return res.data;
};
```

2021-02-23 10:37 UTC, dididy commented on src/api/index.ts
> +export default { createQuestion };
저번에 컴포넌트 관련 index.ts 설명해주신걸로 미루어보면 여기에도 default를 붙이지 않는게 낫지 않나요?

2021-02-23 10:39 UTC, dididy approved these changes
선형님이 짚어주신 부분만 논의 후 적용하면 될 것 같습니다.

수고하셨습니다!

2021-02-24 13:40 UTC, BKJang commented on src/api/controllers/utils.ts
> +  message: string | number;
어떤 형식으로 하면 될지 애매해서 했었는데 협의한대로 하면 string이면 되겠네요 수정하겠습니다 👍

2021-02-24 14:17 UTC, BKJang commented on src/api/index.ts
> +export default { createQuestion };
맞습니다. 제가 테스트하고 나서 바꾸질 않았네요ㅠ

2021-02-24 14:17 UTC, BKJang commented on src/api/controllers/utils.ts
> +    const data: any = await parseResult(res.data);
수정했습니다.

2021-02-24 14:17 UTC, BKJang commented on src/api/controllers/utils.ts
> +    });
좋습니다. 수정했습니다.

2021-02-24 14:17 UTC, BKJang commented on src/api/controllers/utils.ts
> +const parseResult = (res: TApiReturn): any => {
수정했습니다.

2021-02-24 14:17 UTC, BKJang commented on src/api/controllers/utils.ts
> +  message: string | number;
수정했습니다.

2021-02-24 14:17 UTC, BKJang commented on src/api/controllers/Question.ts
> +}
수정했습니다.

2021-02-25 00:16 UTC, SeonHyungJo commented on src/api/controllers/Question.ts
> +}
죄송합니다

개인적으로는 type이 좋다생각했는데 컴파일 시점을 생각하면 Interface가 더 좋네넹 @BKJang

2021-02-25 14:40 UTC, SeonHyungJo approved these changes
수고하셨습니다. 승인합니다.

2021-02-25 14:40 UTC, merged