[common/sass] 공통 sass color, valuable, mixin 추가
Im-D/your-voice-front pull request #4
Opened 2021-02-22 13:56 UTC by SeonHyungJo

# 공통 SASS 작업

## Color

메인 색상으로 포함한 기본 Black White를 추가하였습니다. 모든 색상은 Figma의 색상을 기본으로 구성하였습니다.

```scss
// Black Color
$black: #222222;

// White Color
$white: #ffffff;

// Gray Color
$gray06: #3d3d3d;
$gray05: #7a7a7a;
$gray04: #b4b4b4;
$gray03: #c8c8c8;
$gray02: #e8e8e8;
$gray01: #f8f8f8;

// Main Color
$main01: #D4A5A5;
$main02: #FFECDA;
$main03: #F9FFEA;
$main04: #A6D0E4;
```

## Valuable

주로 사용할 Font Size를 설정하였습니다. Font-size를 사용할 때는 아래의 크기를 사용해주세요.

```scss
$HEADER_HEIGHT: 56px;

$TITLE_01: 32px;
$TITLE_02: 28px;
$TITLE_03: 24px;
$TITLE_04: 20px;
$TITLE_05: 18px;
$TITLE_06: 16px;

$TEXT_01: 16px;
$TEXT_02: 14px;
$TEXT_03: 12px;
$TEXT_04: 10px;
$TEXT_05: 8px;
$TEXT_06: 6px;
```

## Mixin

media query 부분과 가장 많이 사용하는 flex를 mixin으로 구성하였습니다.

```scss
$desktop: "(min-width: 756px)";
$tablet: "(min-width: 401px) and (max-width: 756px)";
$mobile: "screen and (max-width: 400px)";

@mixin desktop {
  @media #{$desktop} {
    @content;
  }
}

@mixin tablet {
  @media #{$tablet} {
    @content;
  }
}

@mixin mobile {
  @media #{$mobile} {
    @content;
  }
}

@mixin flex_col ($justify-content: center, $align-items: center) {
  display: flex;
  flex-direction: column;
  justify-content: $justify-content;
  align-items: $align-items;
}

@mixin flex_row ($justify-content: center, $align-items: center) {
  display: flex;
  flex-direction: row;
  justify-content: $justify-content;
  align-items: $align-items;
}
```

2021-02-23 10:47 UTC, dididy requested changes
수고하셨습니다!

2021-02-23 10:47 UTC, dididy commented on src/styles/_color.scss
> +$main04: #A6D0E4;
main으로 퉁치면 조금 구분하기 어렵지 않을까요? 

<img width="240" alt="Screen Shot 2021-02-23 at 7 40 48 PM" src="https://user-images.githubusercontent.com/16266103/108832918-7dacdd80-760f-11eb-9c0e-bcb7c171bcd5.png">

마지막 라인 공백?이 있으면 좋을 것 같습니다~

2021-02-23 10:47 UTC, dididy commented on src/styles/_mixin.scss
> +  @media #{$desktop} {
이게 저번에 말씀해주신 변수로 편하게 사용하는 방법이군요!

2021-02-23 10:47 UTC, dididy commented on src/styles/_mixin.scss
> +}
와 이거 매번 정의하기 귀찮았는데 이렇게 쓰는 방법이 있군요..

2021-02-24 11:11 UTC, SeonHyungJo commented on src/styles/_color.scss
> +$main04: #A6D0E4;
계절별로 바꿔줄지 몰라서 했는데 혹시 main말고 뭐가 좋을까요?

2021-02-24 14:20 UTC, BKJang commented on src/styles/_mixin.scss
> +}
약간 styled-component에서 매개변수로 넘기는 것과 비슷한 방식으로 보여지네요.
sass 쓸만하겠는데요? 좋습니다 👍

2021-02-24 14:20 UTC, BKJang approved these changes
전 승인하겠습니다. 작업하신 부분 회의 때 한 번 리뷰하면서 interface만 서로 이해가 잘 되면 될 것 같아요.
고생하셨습니다 👍

2021-02-24 16:04 UTC, dididy commented on src/styles/_color.scss
> +$main04: #A6D0E4;
아 그런 측면이라고 한다면 숫자로 구분하는게 오히려 좋을지도 모르겠습니다!

2021-02-24 16:05 UTC, dididy approved these changes

2021-02-25 14:54 UTC, merged